glassdoor_urls = ["https://www.glassdoor.com/Job/us-data-analyst-jobs-SRCH_IL.0,2_IN1_KO3,15.htm?clickSource=searchBox",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP2.htm?includeNoSalaryJobs=true&pgc=AB4AAYEAHgAAAAAAAAAAAAAAAfwEwZEAUwECAQcQBgJieB%2FoSZx7dibMT5XQe3%2Bv38zBOqUKkAuGLAbvi4MPDHtJmqYsOjIqX1YekTHOkGJeev5DfO0S%2BcPV1fMSeq5SMlAEKd3f0HC%2FWWerAAA%3D",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP3.htm?includeNoSalaryJobs=true&pgc=AB4AAoEAPAAAAAAAAAAAAAAAAfwEwZEAhQECAQ4gCwEm9%2Fe4f5Dxcvc9gsRZH9EFK95sw75UDzRfPNC6F30BpspSZGBu36nPWp0lvLHV%2BAccjTqxv%2F%2FNNrYB5smMWEmzWoTrXfPwDsxLwZOkSuVYs0FeB1IvxlDNtBUti2LBOuxxhBXKLK1qZ4Fk5zCzmgtk0cdFB9siH4v1lD70caMAAA%3D%3D",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP4.htm?includeNoSalaryJobs=true&pgc=AB4AA4EAWgAAAAAAAAAAAAAAAfwEwZEAsAECARtMCwJZnXWq24c9yM0QXEQ6q0PO909j3Vm3ShQpgcKnyqLj7Kqu%2F1SNrZHFL5fF6WXV6Ht7ud4tLcg2d%2BfbJugL9GJ5%2FTlGRuc32Dh9jboa13teHCjKVBHDLXv%2B8V2tb0%2FsipZtgva8qmv6%2BNnxTWgIhEia2k0ZTMY27k8Phx8pH5%2FEJIXc8mnN1gCsoUX5I%2BpRvmid4wY8Rm2ubrT5q1y8Ub%2FEhXwfAL98NOIkAAA%3D",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP5.htm?includeNoSalaryJobs=true&pgc=AB4ABIEAeAAAAAAAAAAAAAAAAfwEwZEA1AECAR9MCy6QjnZo8rWZMlJikEDn4LtfRJ83u1832LiUFnWXPc8GBDZoFmIYdZCzNDCc6CV7b30JwQHDrmnMnh56MZxyK5nRquTmHXAJDLeMubxGVz5oPttQ1onVB3IVXMHyOpujSG931q2Dg1jHUtErtBLWt5jR6mmqCqhoK4NC9Fdo%2FHhJvh36foi4b2Wa9Ss7IeSPOiPmiZLzQdljw5Kc0VVzr2DI26sSTzooh5ZUUbT1E46YgppFsSAcON86%2FPZQhRiKwsvva4vUcXruOUXF9d%2FaAAA%3D",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP6.htm?includeNoSalaryJobs=true&pgc=AB4ABYEAlgAAAAAAAAAAAAAAAfwEwZEA9QECASNMDgDiaCo8DSdjNqnHdIQju1dcDccEpVyNqdoeK58YA1DukBFXU0JqKosPLw9F%2BXYXG0pIGCG7RwKQ%2FbnUsqi%2BOcoseo6IqDWir4ANZ3vOhlhsLlFEc5L2vrmnyTEJ2VXn92jqffsGEBOX3woX63eCHUAWmiF0emDBBfgd5Sy2KvphfFe0BuodpeoLzciU8b2IAd42oLoIh5hN3G0bSqhD08uCxF9f4QVLTFQF6DQxiAwxiv8XRM1z5%2Fkfb0oXZG6EG1R95%2FmxUPDGC2M1YVBlM%2FQuD3CYLs0zxBz896vnRwD9XjpNfBXMlJH7b0uMSxOBAAA%3D",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP7.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP8.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP9.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP10.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP11.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP12.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP13.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP14.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP15.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP16.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP17.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP18.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP19.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP20.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP21.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP22.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP23.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP24.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP25.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP26.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP27.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP28.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP29.htm?includeNoSalaryJobs=true",
                  r"https://www.glassdoor.com/Job/united-states-data-analyst-jobs-SRCH_IL.0,13_IN1_KO14,26_IP30.htm?includeNoSalaryJobs=true"
                  ]
url_header = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) '
              'AppleWebKit/537.11 (KHTML, like Gecko) '
              'Chrome/23.0.1271.64 Safari/537.11',
              'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
              'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
              'Accept-Encoding': 'none',
              'Accept-Language': 'en-US,en;q=0.8',
              'Connection': 'keep-alive'}
